import {createAsparagus} from "./seeds/asparagus.js"
import {createCorn} from "./seeds/corn.js"
import {createPotato} from "./seeds/potato.js"
import {createSoybean} from "./seeds/soybean.js"
import {createSunflower} from "./seeds/sunflower.js"
import {createWheat} from "./seeds/wheat.js"
import {addPlant} from "./field.js"

export const plantSeeds = (plan) => {

/* This function populates an array with plant objects based
on the array of plant names generated by the plantSeeds function.*/

let planted = []

    for (const step of plan) { 
        for (const subStep of step){
            switch (subStep) {
                case "Asparagus":
                    planted = createAsparagus()
                    break;
                case "Potato":
                    planted = createPotato()
                    break;
                case "Sunflower":
                    planted = createSunflower()
                    break;
                case "Wheat":
                    planted = createWheat()
                    break;
                case "Soybean":
                    planted = createSoybean()
                    break;
                case "Corn":
                    planted = createCorn()
                    break;
}

/* This function pushes the current value of the plan array into 
the addPlant function in field. The resultant array can then be
accessed in main through the usePlants() function. */

       addPlant(planted)

}
}
}